name: 'Use Reusable SonarQube Workflow'

on:
  pull_request:
    types: ['opened', 'synchronize', 'reopened']
  push:
    branches:
      - main

jobs:
  sonarQubeScan:
    uses: harivignesh-git/test-reuse-workflow/.github/workflows/reference.yaml@main
    with:
      projectKey: 'TrimbleCloudXops.xOpsStandards:github-repository-management'
      projectName: 'github-repository-management'
      sources: '.,.github/workflows/terraform.yaml,.github/workflows/sonarscan.yaml,.github/workflows/validate_repo_name.yaml'
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
