name: Check Comments in Files

on: [push, pull_request]

jobs:
  check-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y grep

      - name: Debug - List all files
        run: find . -type f
      
      - name: Find files without comments
        run: |
          # Define file patterns and their respective comment regex
          declare -A patterns
          patterns["js"]='//|/\*'
          patterns["py"]='#|"""|'\'''\'''
          patterns["java"]='//|/\*'
          patterns["html"]='<!--'
          patterns["rb"]='#'
          patterns["php"]='//|/\*'
          patterns["css"]='/\*'
          patterns["cs"]='//|/\*'
          patterns["sh"]='#'
          patterns["dockerfile"]='#'
          patterns["yaml"]='#'
          patterns["go"]='//|/\*'
          patterns["ps1"]='#'
          patterns["tf"]='#|/\*'
          patterns["bicep"]='/\*'
          
          failed=0
          
          for ext in "${!patterns[@]}"; do
            for file in $(find . -type f -name "*.$ext"); do
              echo "Checking: $file"
              if ! grep -qE "${patterns[$ext]}" "$file"; then
                echo "❌ No comments found in: $file"
                failed=1
              else
                echo "✅ Comments found in: $file"
              fi
            done
          done
          
          if [[ "$failed" -eq 1 ]]; then
            echo "❌ Some files are missing comments. Please add comments."
            exit 1
          else
            echo "✅ All files contain comments."
          fi
